### ISSUE TITLE
Costume Avatar moves when using arrow keys in imported file container

### ISSUE THREAD

**Issue by chriscola** [TheArmoredGarage/Armorsmith-Designer#2]
When using keys to select a file to add to the avatar, using up and down keys causes the main container to move. The avatar on the podium moves in regards to the direction of the arrow keys used.

![avatar](https://user-images.githubusercontent.com/32226262/43354059-ddc0d8a4-91f9-11e8-9639-a932353d2391.PNG)

**Comment by TheArmoredGarage** [comment]
Only allowing keyboard input when any of the 3 main 3d windows have input. Fixed in version 1.1.13.1
