### ISSUE TITLE
Fix RenderTarget resizing

### ISSUE THREAD

**Issue by TheArmoredGarage** [TheArmoredGarage/Armorsmith-Designer#25]
Looks like some of the work to fixup the resizing in the 32-bit version hasn't been brought over.

**Comment by tmilker** [comment]
Is this what causes the unfold 2D and 3D windows to appear low resolution and especially bad when zoomed out or should I post a new issue?

**Comment by TheArmoredGarage** [comment]
Yeah, it's only on certain machines. It's on my list to fix.
________________________________

**Comment by tmilker** [comment]
If you need a tester, let me know because it happens on mine. WIndows 10, 1080Ti on a 4K monitor(native resolution no scaling).
