### ISSUE TITLE
New 64 bit updste - program not executing.

### ISSUE THREAD

**Issue by AlxMach** [TheArmoredGarage/Armorsmith-Designer#32]
I down loaded the new 64bit version and in was working 2 days ago. Now it is not opening, I get to the black screen and stops. I tried to reinstall but got the same results.

**Comment by Cornerpocket87** [comment]
I am having the same issue as well. worked last night, but went to open today and black screen then nothing. running version 1_1_14_5x64

**Comment by TheArmoredGarage** [comment]
I believe these issues have been resolved. Let me know if still occuring.
