### ISSUE TITLE
1.1.15.1 - Crash on save.

### ISSUE THREAD

**Issue by tbruyere71** [TheArmoredGarage/Armorsmith-Designer#34]
recreation:
- new armor (uses my customised avatar)
- import an stl
- save
- crash leaves a zero byte armor file behind

event viewer show a crash, but no real info. Is there a log somewhere you'd like to see?

**Comment by TheArmoredGarage** [comment]
I believe all the save issues have been buttoned up. Let me know if this is still occuring.
