### ISSUE TITLE
How to turn off automatic measurement readjustment?

### ISSUE THREAD

**Issue by N0valynn** [TheArmoredGarage/Armorsmith-Designer#40]
Trying to enter my measurements for the first time. When I enter one size all the others readjust themselves. I'm very tall so I imagine it's trying to keep it proportional, but I need it to stop. Is there a way to turn it off?

**Comment by TheArmoredGarage** [comment]
It sounds like you might have been adjusting the overall height while entering measurements. This changes the overall scale of the Avatar. You only want to adjust this once to set the scale and then adjust the other measurements to keep the correct overall height.
