### ISSUE TITLE
Pieces not retaining shape when importing pdo’s to Armorsmith

### ISSUE THREAD

**Issue by collinE83** [TheArmoredGarage/Armorsmith-Designer#41]
A lot of my unfolds look fine in Pepakura Designer, but when the pdo is imported into Armorsmith, they’re assembled wildly and no long simple, solid pieces. What was once a nice and pretty unfold is now a bit of a mess. 

My theory is it’s an issue with pieces that have had the “join adjacent edges” tool used on them in Pepakura Designer. Almost like Armorsmith isn’t reading which edges the polygons are joined to and so it does it’s best guess. I can provide pictures and files that do this if needed.

**Comment by TheArmoredGarage** [comment]
Correct, there's unfortunately nothing stored in the PDO to indicate which edges are joined. This can be resolved in Armorsmith by using the Join Adjacent Edges tool and welding those edges back together.
