### ISSUE TITLE
Mannequin/objects stop working alltogether

### ISSUE THREAD

**Issue by Lorenzacosplay** [TheArmoredGarage/Armorsmith-Designer#50]
Hello,

I've recently purchased armorsmith and started adding armor pieces (using obj files) to my mannequin. However, as soon as I import and attach the 2nd object, the mannequin and the 2nd object become unclickable and whenever I try to select it using the top right menu it still operates on the first object. Now when I try the 2nd object a third and a fourth time, the screen glitches a bit, the first object disappears from the menu and I still can't put the armor pieces on the mannequin.

It ended up getting so messy I couldn't translate or scale anything anymore so I closed it, started over and tried different files but got the same results.

Is there any way to put multiple armor pieces on my mannequin without the program having a stroke?

![armorsmith](https://user-images.githubusercontent.com/54511887/63655194-8f48c700-c785-11e9-8192-69f30c6cd483.png)

**Comment by lucky13sign** [comment]
same problem except  program crashes

**Comment by TheArmoredGarage** [comment]
I'd suggest grabbing the latest build, this seems like maybe you grabbed a bad update. Definitely no problems attaching multiple parts.
