### ISSUE TITLE
mirrored pieces in unfold 

### ISSUE THREAD

**Issue by notabella** [TheArmoredGarage/Armorsmith-Designer#54]
There are some pieces in my unfold that are mirrored and thus do not have an attach point anymore and I'm wondering if this is a bug that can be fixed or maybe its just my model but have had it happen with several models maybe its worth implementing a mirror button for parts like this? for now I'm just printing out this puzzle and assembling it in paper form lol. Keep up the good work!!

**Comment by TheArmoredGarage** [comment]
In general foam patterns are only unfolded for a single half. There's a "Mirror Workspace" option in the properties to flip the patterns if you'd like to print or export the vectors out for them. Thanks for the comment :D
