### ISSUE TITLE
measurement avatar VS model

### ISSUE THREAD

**Issue by Renaldo38** [TheArmoredGarage/Armorsmith-Designer#55]
when i scale my boots  they are much smaller with same measurements of the avatar feet..

![Screenshot 04-13-2020 16 31 04](https://user-images.githubusercontent.com/63597830/79128849-776d9400-7da4-11ea-998b-3818d9b04931.png)
![Screenshot 04-13-2020 16 30 48](https://user-images.githubusercontent.com/63597830/79128851-78062a80-7da4-11ea-9a64-6a717f3ba7bb.png)

**Comment by TheArmoredGarage** [comment]
All scaling issues should be resolved.
