### ISSUE TITLE
Request - Body Measuring guide

### ISSUE THREAD

**Issue by HappyHappyFunTime** [TheArmoredGarage/Armorsmith-Designer#56]
I would like to request a feature, please. 

In the help, could you put either a link to or a short, comprehensive guide of how to measure for each of the sizes on the Avatar model. 

I was able to find most of them digging through measuring guides for sewing, but at least "Head Height" I'm not sure what exactly you're asking for here? Measure from top of the head on a Z plane? Top of head down to? Jaw? Chin? Or is it one from the center, top of the head, going down to some point? Example - https://www.youtube.com/watch?v=TRcsL8X59L4

**Comment by TheArmoredGarage** [comment]
I don't think measuring guides for sewing will help too much. What you want to do is to click on the part and check what two points on the avatar the measurement actually corresponds to.
