### ISSUE TITLE
Error when launching installer in Windows 10

### ISSUE THREAD

**Issue by vincentstarjammer** [TheArmoredGarage/Armorsmith-Designer#57]
I am trying to install Armorsmith Designer in Windows 10 and I get the following error:

![image](https://user-images.githubusercontent.com/66815562/84466787-d1a7aa00-acac-11ea-9c2b-88b750bb2398.png)

There is no other option to proceed, only "Don't Run".

**Comment by TheArmoredGarage** [comment]
I'm not familiar with Defender SmartScreen but you'll likely need to disable it to run the installer.
