### ISSUE TITLE
All limbs on avatar scaling when I just change the size of one part

### ISSUE THREAD

**Issue by tvanhelene** [TheArmoredGarage/Armorsmith-Designer#60]
Hello,

Whenever I try to scale a body part, like the thigh, the rest of the body scales with it. This is making it impossible to accurately scale the avatar, as whenever I change one limb, all the other limbs change slightly as well. 

here is a gif of the issue
![ezgif-5-2d5e825ad746](https://user-images.githubusercontent.com/27146681/91193323-f5339b80-e6c4-11ea-96a4-a4de57c8ec35.gif)

**Comment by TheArmoredGarage** [comment]
This has been fixed with the new avatar
